#     _____             __  _ __
#    / ___/____ _____  / /_(_) /_____
#    \__ \/ __ `/ __ \/ __/ / __/ __ \   Santito
#   ___/ / /_/ / / / / /_/ / /_/ /_/ /   https://github.com/San-tito
#  /____/\__,_/_/ /_/\__/_/\__/\____/    https://gitlab.com/santito
#

import = ["~/.config/alacritty/colors.toml", "~/.config/alacritty/fonts.toml"]

[shell]
program = "/bin/zsh"
args = ["--login"]

[env]
TERM = "xterm-256color"

[window]
position = "None"
dynamic_padding = true
decorations = "full"
opacity = 1.0
blur = false
startup_mode = "Windowed"
dynamic_title = true
class = { instance = "Alacritty", general = "Alacritty" }
decorations_theme_variant = "None"

[window.dimensions]
columns = 82
lines = 24

[window.padding]
x = 10
y = 10

[selection]
save_to_clipboard = true

[scrolling]
history = 10000
multiplier = 3

[cursor]
vi_mode_style = "None"
blink_interval = 750
blink_timeout = 5
unfocused_hollow = false
thickness = 0.15

[cursor.style]
shape = "Block"
blinking = "On"

[mouse]
hide_when_typing = false

[[hints.enabled]]
command         = "xdg-open"
hyperlinks      = true
post_processing = true
persist         = false
mouse.enabled   = true
binding         = { key = "U", mods = "Control|Shift" }
regex           = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"

