#     _____             __  _ __
#    / ___/____ _____  / /_(_) /_____
#    \__ \/ __ `/ __ \/ __/ / __/ __ \   Santito
#   ___/ / /_/ / / / / /_/ / /_/ /_/ /   https://github.com/San-tito
#  /____/\__,_/_/ /_/\__/_/\__/\____/    https://gitlab.com/santito
#

[colors.primary]
background = "#090A0B"
foreground = "#E6DFE0"

[colors.normal]
black   = "#282828"
red     = "#e06c75"
green   = "#98c379"
yellow  = "#e5c07b"
blue    = "#61afef"
magenta = "#c678dd"
cyan    = "#56b6c2"
white   = "#E6DFE0"

[colors.bright]
black   = "#282828"
red     = "#e06c75"
green   = "#98c379"
yellow  = "#e5c07b"
blue    = "#61afef"
magenta = "#c678dd"
cyan    = "#56b6c2"
white   = "#E6DFE0"
