#     _____             __  _ __
#    / ___/____ _____  / /_(_) /_____
#    \__ \/ __ `/ __ \/ __/ / __/ __ \   Santito
#   ___/ / /_/ / / / / /_/ / /_/ /_/ /   https://github.com/San-tito
#  /____/\__,_/_/ /_/\__/_/\__/\____/    https://gitlab.com/santito
#

[font]
size = 16

builtin_box_drawing = true

[font.normal]
family = "JetBrainsMono Nerd Font"

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0
